### ISSUE TITLE
The movie trailer continues to play even after clicking the closing button (x) 

### ISSUE THREAD

**Issue by GeovannaBorges** [lazyjinchuriki/cinephile#1]
Hello! I really loved the idea of your project, and its execution with vanilla JS is awesome! But I found a small issue: Once I play the trailer, and then try to close it, by clicking the x button, the sound of the video keeps playing, and just stops when the video is over or when I play another trailer on. 
![github project cinephile - issue](https://github.com/lazyjinchuriki/cinephile/assets/127786376/bce7a571-169f-4a50-84cd-dc5106afa5a2)

As you can see in the picture, there's no video playing, but the icon I highlighted above continues to appear, even though the trailer has been closed.

**Comment by lazyjinchuriki** [comment]
Hi there,
Best of luck 👍🏻 
Create a pull request, I'll merge it.
