### ISSUE TITLE
Hover Effects For Cards 

### ISSUE THREAD

**Issue by Surya-V-28** [lazyjinchuriki/cinephile#11]
The hover effects of the cards are not key board responsive when i move between the cards using tab 

its overflow with other elements , please have a look 

please assign me under the hacktober fest , i would like to work  on it . 

![image](https://github.com/lazyjinchuriki/cinephile/assets/102609082/681e9b4f-a228-4465-93ec-153dd2f244cb)

**Comment by Surya-V-28** [comment]
@lazyjinchuriki  it solved  ?

**Comment by lazyjinchuriki** [comment]
No, do you want me to assign this issue to you

**Comment by Surya-V-28** [comment]
@lazyjinchuriki , Yeah , i am planning on work on it
