### ISSUE TITLE
The z-index for the Release date is overlapping the trailers

### ISSUE THREAD

**Issue by lazyjinchuriki** [lazyjinchuriki/cinephile#15]

**Comment by Nwakaego-Ego** [comment]
Hi, Please assign this issue to me and I will also appreciate if you give more context , a screenshot will be really great

**Comment by the-shivam-gupta** [comment]
If possible, please assign the problem to me as I have understood it.

**Comment by vedantpotekar** [comment]
Hello, I am participating in hacktoberfest 2023, and I have solved the issue in which the release date of any movie was overlaying on the movie's trailer. 
I have put a pull request for the same. Please accept and merge my PR. Thanks.

**Comment by Nwakaego-Ego** [comment]
It wasn't suppose to feel like a competition, it's a good first issue, it's hacktoberfest issue, the original idea is allowing first time contributors find their footing in the world of open source.

Well done @lazyjinchuriki

**Comment by lazyjinchuriki** [comment]
The issue #25 is similar to this you can fix that but I'll still prefer the one who does it first.
