### ISSUE TITLE
update header 

### ISSUE THREAD

**Issue by MAVERICK-VF142** [lazyjinchuriki/cinephile#16]
1. addition of logo and name in header

**Comment by lazyjinchuriki** [comment]
It should be mobile responsive.

**Comment by GD0910** [comment]
Do you have a logo ?

**Comment by lazyjinchuriki** [comment]
You can add this one :
https://avatars.githubusercontent.com/u/92175633?v=4

**Comment by MAVERICK-VF142** [comment]
@lazyjinchuriki thanks

**Comment by GD0910** [comment]
> You can add this one : https://avatars.githubusercontent.com/u/92175633?v=4

Ok I can try

**Comment by GD0910** [comment]
> @lazyjinchuriki thanks. Please assign it to me

i am new to open source and it will be great for me to work with you in this project 

additional improvement : We can swtich the search bar to right side besides tv-show logo so that we can insert our website logo and name

Need your thoughts on this as well @lazyjinchuriki @MAVERICK-VF142

**Comment by lazyjinchuriki** [comment]
You need to first fork this repo,
Then clone it to your pc/laptop
After cloning you have to add that image to the header.
The you have to push those changes first to your forked repo, come back to that repo you'll see an option to create a pull request.
That's it.

**Comment by GD0910** [comment]
ok will try it can you put this issue under hacktoberfest tag 
Thankyou .Will start working on this issue

**Comment by GD0910** [comment]
@lazyjinchuriki  Any changes or should i raise PR
![image](https://github.com/lazyjinchuriki/cinephile/assets/88530462/fa5e0a8d-1575-4b9b-ab5f-a859253197c9)

**Comment by lazyjinchuriki** [comment]
Decrease the size of logo to fit perfectly with the tv shows switch button.

**Comment by MAVERICK-VF142** [comment]
@lazyjinchuriki @GD0910 This kind of seems unethical me raising the issue and you are not assigning the issue to me and someone random barges into someone else's issue and starts working on it not good open source practice

**Comment by lazyjinchuriki** [comment]
You should've told me that you are planning on working on it and not just pointing an Issue.
Everybody else asks to assign them the issue and I have assigned each and every one.
Now it's not my fault that someone else came and grabbed your issue.

**Comment by GD0910** [comment]
@lazyjinchuriki can u assign me so that my contibution can be seen and please add hacktoberfest tag for this issue
Will raise the PR in some time
