### ISSUE TITLE
On Hovering on the Genre - hand cursor to be shown

### ISSUE THREAD

**Issue by HarineMurugan** [lazyjinchuriki/cinephile#2]

**Comment by HarineMurugan** [comment]
https://github.com/lazyjinchuriki/cinephile/pull/3

**Comment by Khitishgithub** [comment]
Hello sir ,can you assign this issue to me ?

**Comment by lazyjinchuriki** [comment]
> Hello sir ,can you assign this issue to me ?

The pull request has already been merged for this issue.
You can check this project to find good first issues :-
https://lazyjinchuriki.github.io/pokedex

I'll gladly merge your pull requests there. 😄
