### ISSUE TITLE
idea : navbar additions

### ISSUE THREAD

**Issue by rohitroy-github** [lazyjinchuriki/cinephile#21]
I think we can add a logo or the project name on the leftmost side of the navbar like any standard navbar and put the search input bar in the middle and the movie-series button on the rightmost side. I think this will look good on the page. 

![image](https://github.com/lazyjinchuriki/cinephile/assets/68563695/1697e1af-920d-4a03-a845-e1c71f351c6e)

You can assign this issue to me if you think it's required. The issue will be in accordance with Hacktoberfest!

**Comment by lazyjinchuriki** [comment]
I have already assigned you for that in a different issue.
