### ISSUE TITLE
fix: searchbar not working

### ISSUE THREAD

**Issue by Shubhamm33** [lazyjinchuriki/cinephile#22]
Searchbar not working when typed any movie name
This can be added as a feature, that the page updates with the movie name or series name....
working on it

https://github.com/lazyjinchuriki/cinephile/assets/38568811/c3a3d00f-14ea-40d3-841f-59e91653df19

**Comment by lazyjinchuriki** [comment]
I'm assigning this issue to you.
Best of luck

**Comment by Shubhamm33** [comment]
**Changes:**
- Single Layout added as base template
- Movies and Tv are fetched and displayed into single html page
- search functionality added which will search depending if its movie or Tv and display
https://github.com/lazyjinchuriki/cinephile/assets/38568811/018dcdcd-65b8-49a0-8abc-9329b06bd6e2

**Comment by lazyjinchuriki** [comment]
Kindly create a pull request

**Comment by Shubhamm33** [comment]
Hello sir, 
you've already merged this?
the search functionality with single page folder

**Comment by lazyjinchuriki** [comment]
![Screenshot_20231007_142136_Soul.jpg](https://github.com/lazyjinchuriki/cinephile/assets/92175633/e51ffb42-0111-4dc8-80a7-fdae276ba88f)

The search does not work until I press enter.

**Comment by Shubhamm33** [comment]
its the layout.html file
No, you don't have to press enter, just type the name in the searchbar, there a slight delay added 
otherwise it will fetch requests based on each typed character in the searchbar (not a good approach)
i'll go through it again and get back
let me know if you face issue

**Comment by lazyjinchuriki** [comment]
Ohh! May bad 😅
