### ISSUE TITLE
fix: base template duplication

### ISSUE THREAD

**Issue by Shubhamm33** [lazyjinchuriki/cinephile#24]
Please keep one base layout as both TV and Movies have same layout and same functionality and working,
instead of having 2 html pages, try to integrate both pages into 1 
(not just the html, but tv and movie JS should be working on the integrated html )

**Comment by lazyjinchuriki** [comment]
That's a great idea,
Can you work on that?

**Comment by Shubhamm33** [comment]
Yes sir i'm currently doing this
after this the search function can be more easy to implement
