### ISSUE TITLE
UI Changes and Imporvement - Hacktoberfest

### ISSUE THREAD

**Issue by Nitish36** [lazyjinchuriki/cinephile#28]
Hey there I would like to work on this repo basically regarding the UI improvement and also to make the appearance very good-looking. I will try to give it a netflix theme type feel. Please assign this issue under hacktoberfest-accepted.

Thank You :)

**Comment by Nitish36** [comment]
Hey there

I have made the changes in the UI as possible. Hope you will like it :)


https://github.com/lazyjinchuriki/cinephile/assets/91598274/5e9fb449-40e6-4400-9754-5b3fb8ae1bb2

**Comment by lazyjinchuriki** [comment]
That's a little too much.
I'm  Sorry but I can't merge that in the main branch. A separate branch I can do

**Comment by Nitish36** [comment]
Okay
