### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by CharithaCS** [lazyjinchuriki/cinephile#40]
Hello! I'd like to improve the footer of your website. I can add a back-to-top button since it requires scrolling all the way up. Also, the UI can be made better and more content can be added to the footer. Please assign me this if you feel this is a good idea. Thanks :)

**Comment by lazyjinchuriki** [comment]
Sure thing but remember to maintain the overall UI and not just rewrite everything.
Also can you please improve the social icons on the footer?

**Comment by CharithaCS** [comment]
Yeah sure! I'll maintain the uniformity. About the icons, I had it in my
mind. I'll do it. Thanks.
