### ISSUE TITLE
bug: Remove console.log

### ISSUE THREAD

**Issue by accodes21** [lazyjinchuriki/cinephile#42]
Remove ```console.log``` from scripts which are not required.

Screenshot:
![Screenshot (392)](https://github.com/lazyjinchuriki/cinephile/assets/101868279/f707fe38-9c07-4e26-83b9-901b0353636a)

**Comment by lazyjinchuriki** [comment]
Once the hacktoberfest is over I'm gonna review every thing and then I'll remove them
