### ISSUE TITLE
Add Simple login for users and adding save to list option

### ISSUE THREAD

**Issue by roxoho** [lazyjinchuriki/cinephile#47]
Hey, I think adding simple login in this project would be good.

Also, we can add add to list option or "+" icon on each movies and tv shows, so the users can save their findings while searching.

I would love to work on it, if you want to add this functionality in your project. I am interested to contribute on this project, so if new ideas come up to my mind, I would let you know.

- [ ] Login functionality
- [ ] Add to list option

**Comment by lazyjinchuriki** [comment]
That's a big responsibility.
Can you handle it without breaking the existing code?

**Comment by roxoho** [comment]
I will try to do my best, this will take good amount of time. I will get back to you after I have implemented the changes, then you can decide whether to update the changes to the project or keep the existing project.

I am also doing this for my self learning.

**Comment by lazyjinchuriki** [comment]
I'm assigning this issue to you under hacktoberfest.
Best of luck

**Comment by roxoho** [comment]
ok, I will try my best

**Comment by roxoho** [comment]
Hey, you were right. This isn't as simple as I thought it would be.

I don't think at my current level, I can handle this alone.

Sorry for this, I am closing this issue.
