### ISSUE TITLE
Inconsistent Search Bar location

### ISSUE THREAD

**Issue by WeiJian123-tech** [lazyjinchuriki/cinephile#49]
Hello, in addition to my Uncaught Reference Error Issue I'd like to bring attention to the header for `index.html` and `tvshows.html`. When I press toggle button at the top-right hand corner of the header, I noticed that the search bar does not stay in the same place between `index.html` and `tvshows.html` because of your profile pic/icon that is missing in `tvshows.html`. This may make the User Interface (UI) experience inconvenient when searching for movies/TV shows especially when the user wants to switch between movies and TV shows fast.  

![image](https://github.com/lazyjinchuriki/cinephile/assets/55195954/ef8f60e8-ce3e-41b0-873d-20743bff095b)

![image](https://github.com/lazyjinchuriki/cinephile/assets/55195954/24b96f66-ec4f-4283-b697-2fa03159e0aa)

I could make a pull request that includes your profile pic/icon to `tvshows.html` and enlarge the search bar for web/laptops/desktops if you want.

**Comment by lazyjinchuriki** [comment]
Sure go for it.

**Comment by WeiJian123-tech** [comment]
Awesome. 😃

**Comment by DeepRahangdale** [comment]
if the issue is still not solved then would love to work over it. assign me!

**Comment by WeiJian123-tech** [comment]
Sorry @DeepRahangdale, I have already resolved this issue and gotten a pull request. Thank you for volunteering to work over this issue though. 🙂
