### ISSUE TITLE
Feat: Improve UI of back to top button

### ISSUE THREAD

**Issue by akash0708** [lazyjinchuriki/cinephile#51]
Hello @lazyjinchuriki , the current back to top button is available only at the bottom of the website. I think it would be more user friendly if we make it sticky. I will also improve the UI of the button. 

### Sample Idea:
![backtotop](https://github.com/lazyjinchuriki/cinephile/assets/110753356/d5194bd2-93a5-4822-8d76-f13a5e53cb5d)

**Comment by lazyjinchuriki** [comment]
Sure. Go for it!
