### ISSUE TITLE
Customed themed scroll bar

### ISSUE THREAD

**Issue by Seemant-RajSingh** [lazyjinchuriki/cinephile#65]
![image](https://github.com/lazyjinchuriki/cinephile/assets/117286608/afff64a4-ece4-4114-8a6d-b620be282c08)

Can add a custom scroll bar themed as the app
#forhacktoberfest

**Comment by lazyjinchuriki** [comment]
Sure.

**Comment by Seemant-RajSingh** [comment]
please assign this under hacktoberfest, i will be makitng a pull request today itself, thanks
